### ISSUE TITLE
RelationshipType AMENDS is missing

### ISSUE THREAD

**Issue by dotmonk** [CycloneDX/cyclonedx-dotnet-library#141]
Hi,

I'm having trouble converting files from the spdx format due to the conversion not supporting the relationshipType AMENDS.

Example spdx json:
```json
{
  "SPDXID": "SPDXRef-DOCUMENT",
  "name": "most of the data has been deleted for brevity",
  "relationships": [
    {
      "relatedSpdxElement": "DocumentRef-package-something:SPDXRef-DOCUMENT",
      "relationshipType": "AMENDS",
      "spdxElementId": "SPDXRef-DOCUMENT"
    }
  ],
  "spdxVersion": "SPDX-2.2"
}
```
To reproduce, put the above json in a file, "test.spdx.json" and run the cyclonedx-cli built against this library:
```sh
cyclonedx convert --input-format spdxjson --output-format json --input-file test.spdx.json --output-file test.cydx.json
Unhandled exception: System.Text.Json.JsonException: The JSON value could not be converted to CycloneDX.Spdx.Models.v2_2.RelationshipType. Path: $.relationships[0].relationshipType | LineNumber: 6 | BytePositionInLine: 34.
   at System.Text.Json.ThrowHelper.ThrowJsonException(String )
...
```
References:
https://spdx.github.io/spdx-spec/relationships-between-SPDX-elements/#1113-examples
https://github.com/CycloneDX/cyclonedx-dotnet-library/blob/main/src/CycloneDX.Spdx/Models/v2_2/RelationshipType.cs

Extra information(In accordance with contributing guidelines):
the version you are using: 5.1.1 used through https://github.com/CycloneDX/cyclonedx-cli which was built from master
your operating system and version: Ubuntu 20.04.4 LTS
reproducible steps (1 2 3...) that cause the issue including any required files: See above
what you expected, versus what happened: Expected to the file to successfully convert, possibly ignoring the unrecognized relationship type. Instead it failed.
any relevant screenshots and other outputs: See above

Note: This is my first reported issue of this type so I hope I've done it correctly :-)

**Comment by coderpatros** [comment]
Thanks for the report. Very thorough. Which makes it a lot easier to pinpoint the issue.

Looks like it is missing from the SPDX JSON schema. I'll create an issue for it upstream.

**Comment by dotmonk** [comment]
This seems to be fixed upstream now. Does this mean that I have to wait for a new release first from this library and then from cyclonedx-cli? I am unfamiliar with the dotnet build pipeline

**Comment by mtsfoni** [comment]
I assume this is fixed. If there are any more problems, please open a new issue.
