### ISSUE TITLE
Does this project work with dotnet core based applications only?

### ISSUE THREAD

**Issue by LakshmiKiranReddy** [CycloneDX/cyclonedx-dotnet-library#143]
We are looking for creating a SBOM for .Net framework based applications, does this code provide us the support with .net framework based applications or it only supports .net core based applications?

The other question is when creating SBOM is the source completely relayed on nuget packges or does the code create SBOM based on the components part of the solution?

**Comment by coderpatros** [comment]
I think you are probably after this tool https://github.com/CycloneDX/cyclonedx-dotnet.

This project only provides data models necessary for serialization and deserialization of CycloneDX BOMs. But it does target .NET standard so you can use it in framework and core projects as a dependency.

**Comment by LakshmiKiranReddy** [comment]
Thanks Patros for the quick replay, any comment on my second question?
Creating of SBOM will be depending on nuget packages or the components part of the solution?

**Comment by coderpatros** [comment]
It generates the BOM based on nuget packages that are resolved.
