### ISSUE TITLE
Vulnerability class does not contain "Properties" Property

### ISSUE THREAD

**Issue by VijayB2606** [CycloneDX/cyclonedx-dotnet-library#192]
As per [CycloneDXv1.4](https://cyclonedx.org/docs/1.4/json/) specification "vulnerabilities" contains "properties" field. I am using CycloneDX DotNet Library v5.3.0. But, I don't find "Properties" property inside [Vulnerability](https://github.com/CycloneDX/cyclonedx-dotnet-library/blob/main/src/CycloneDX.Core/Models/Vulnerabilities/Vulnerability.cs) class.
I need to use "Properties" field for my custom code. Is it planned to add "Properties" property in the vulnerability class? If yes, by when it will be available?

**Comment by VijayB2606** [comment]
@coderpatros - Requesting you to please help with this.

**Comment by coderpatros** [comment]
Available in v5.3.1
