### ISSUE TITLE
Support CycloneDX 1.5

### ISSUE THREAD

**Issue by candrews** [CycloneDX/cyclonedx-dotnet-library#237]
The CycloneDX specification was updated to version 1.5: https://cyclonedx.org/news/cyclonedx-v1.5-released/

And tools are already updating to support it, such as Trivy with its 0.43.0 release: https://github.com/aquasecurity/trivy/releases/tag/v0.43.0

Can this tool please also support the latest version of the CycloneDX specification?

Looking at https://github.com/CycloneDX/cyclonedx-dotnet-library/blob/v5.4.0/src/CycloneDX.Core/Models/Bom.cs#L71 this tool currently only supports up to 1.4.

**Comment by mtsfoni** [comment]
1.5 Support was released in version 6.0
