### ISSUE TITLE
JSON validation fails for valid timestamps

### ISSUE THREAD

**Issue by lfrancke** [CycloneDX/cyclonedx-dotnet-library#265]
Over in [Rust land](https://github.com/CycloneDX/cyclonedx-rust-cargo/issues/353) @jadamcrain opened an issue that our JSON files are invalid.

cyclonedx-cli fails on timestamps like `2022-12-21T23:54:20.218381200Z` but it works if we chop off two digits at the end ` 2022-12-21T23:54:20.2183812Z`

According to the JSON Schema timestamps are `date-time` fields which are RFC 3339 timestamps. The RFC doesn't specify a maximum number of fractional digits so both timestamps should be correct.

I'm not a .NET expert so take everything past this with a huge grain of salt:
- cyclonedx-cli uses this library
- This library uses [JsonSchema.Net](https://github.com/CycloneDX/cyclonedx-dotnet-library/blob/1e3886b706f866f41ce31976888be5721ed32b82/src/CycloneDX.Core/CycloneDX.Core.csproj#L15) in version 3.3.2 as the dependency to do the actual validation
- In version [4.0.1](https://docs.json-everything.net/rn-json-schema/) of the library (current is 5.3.0) it added support for higher-precision timestamps

As such I suggest to update the dependency to a newer version.
I can submit a trivial PR to update the version number but as I have zero knowledge about .NET tools that might not be enough and it might not build.

**Comment by andreas-hilti** [comment]
I think it will need some adjustments, based on the dependabot PR:
https://github.com/CycloneDX/cyclonedx-dotnet-library/pull/264

**Comment by andreas-hilti** [comment]
I have created a PR to update JsonSchema.Net:
https://github.com/CycloneDX/cyclonedx-dotnet-library/pull/272

**Comment by andreas-hilti** [comment]
It validated successfully when a timestamp "2022-12-21T23:54:20.218381200Z" was used.

**Comment by mtsfoni** [comment]
Lars, it's finally done!

- close

**Comment by lfrancke** [comment]
Thank you!
