### ISSUE TITLE
Update spdx.schema files to v1.0-3.21

### ISSUE THREAD

**Issue by eredwine** [CycloneDX/cyclonedx-dotnet-library#277]
We are attempting to validate boms generated by Syft and Trivy using `cyclonedx-cli`. But, the validation is failing due to the `TTWL` license being in the list of licenses. According to the latest version of the CycloneDX spec, `TTWL` is a valid license. But, it is failing validation because this library is still using `v1.0-3.17` of the `spdx` schema.

**Comment by mtsfoni** [comment]
Schema has been updated to 3.23
