### ISSUE TITLE
Support cdx 1.6

### ISSUE THREAD

**Issue by mtsfoni** [CycloneDX/cyclonedx-dotnet-library#284]
- [x] The ToolChoices de-/serializer could be removed again (just introduced for a workaround)
- [x] Check review remarks on cdx1.6 branch
- [x] Check Codacy Issues
- [x] EnumerateAllComponents needs to be updated as there are more places where components can be used (Formulation>Components, Declarations>Target>Components, Vulnerabilities>Tools>Components, Annotations>Annotator>Component etc.) Maybe similar for services.
- [x] Check new snapshots

This is what should still be open. @andreas-hilti is there anything I am missing?

Another issue is that some 1.5 types are not set up to merge yet, but we can fix this next.

**Comment by thompson-tomo** [comment]
To be evaluated as part of this or at a later time, generate classes based on schema to reduce effort needed.

**Comment by andreas-hilti** [comment]
@mtsfoni This is what I'm aware of, except merging the deprecations branch and a final check on the added/modified snapshots (in particular for the ones with new features).

**Comment by wkoot** [comment]
@mtsfoni thanks for the updates in https://github.com/CycloneDX/cyclonedx-cli/issues/376 https://github.com/CycloneDX/cyclonedx-cli/issues/375.
Will you also update the cyclonedx-cli package after this is finished?

**Comment by mtsfoni** [comment]
closing as resolved
