### ISSUE TITLE
Inconsistent Timestamp Representation in XML and JSON BOM Files

### ISSUE THREAD

**Issue by eugenhoffmann** [CycloneDX/cyclonedx-dotnet-library#298]
I have reported an [Issue](https://github.com/CycloneDX/cyclonedx-dotnet/issues/877) in the cyclonedx-dotnet repository regarding an inconsistent timestamp representation in the generated BOM files. The team has suggested that the issue may be related to the serialization process in the library. Here is the description of the issue:

> I have noticed that the timestamp representation in the XML and JSON BOM files is inconsistent. While both formats are ISO 8601 conform, the XML BOM file contains a timestamp with a precision of up to 7 decimal places for the seconds fraction:
> 
> XML: 2024-05-17T15:50:31.6823708+00:00
> JSON: 2024-05-17T15:50:31Z
> 
> In my opinion, this level of precision is not necessary. Furthermore, the second fractions more than 3 digits are not supported by the Python API [datetime.fromisoformat(date_string)](https://docs.python.org/3/library/datetime.html#datetime.datetime.fromisoformat) method.
> 
> While these differences are not incorrect, they can be confusing and may cause issues when processing the data. I would like to propose that we adopt a consistent timestamp representation across both file formats, ideally using the JSON timestamp format.
> 
> Thank you for considering this issue!

**Comment by fmh093** [comment]
I have the same issue. In my case it prevents me from uploading my BOM file to Dependency Track, it simply rejects it.

**Comment by mtsfoni** [comment]
@fmh093 How do you try to upload them? Just via the web interface?

**Comment by fmh093** [comment]
> @fmh093 How do you try to upload them? Just via the web interface?

Yes

**Comment by mtsfoni** [comment]
I think this was fixed (at least thats what i wrote at the cyclonedx-dotnet issue)
