### ISSUE TITLE
SBOM validation is failing when uploading files generated using the global tool

### ISSUE THREAD

**Issue by thompson-tomo** [CycloneDX/cyclonedx-dotnet-library#302]
I am using the dotnet cyclonedx tool (https://www.nuget.org/packages/CycloneDX) to generate SBOM's using the below command
```
dotnet CycloneDX .\Dashboard-Web\Dashboard-Web.csproj -t -ipr
``` 
Which produces the attached SBOM however when i attempt to upload it using the Dependency Track UI it is failing with the below error
![image](https://github.com/CycloneDX/cyclonedx-dotnet-library/assets/19771933/20b8bc00-342d-49f3-b70f-f56c5135c59a)

This process was working prior to my company enabling sbom validation and they are hesitant to turn it back off hence wanting to get the tool fixed.

Note I have reproduced the issue with both 3.0.5 & 3.0.6 with 3.0.6 being the latest version.

My latest SBOM using 3.0.6 can be downloaded from https://fxs.skidata.com/message/CRdyZd5fSVfGzXr7MJanII with link valid until 3rd June 2024 @mtsfoni

**Comment by mtsfoni** [comment]
Problem is that pkg:nuget/RabbitMQ.Client@6.8.1 has 2 licenses nodes

The fix is already prepared, I just hope/wait for a review of its original author, who is a very active contributor:
#301

As soon as it's merged, I am going to release new versions of the library and the generator.

**Comment by thompson-tomo** [comment]
Great thanks for the quick reply. Will await the fix.

**Comment by thompson-tomo** [comment]
thanks @mtsfoni i can confirm i can now upload SBOM's following the update. Thanks again
