### ISSUE TITLE
Please update this example due to the deprecation of the JSON library.

### ISSUE THREAD

**Issue by chaoscode** [CycloneDX/cyclonedx-dotnet-library#316]
https://github.com/CycloneDX/cyclonedx-dotnet-library/blob/main/docs/articles/getting-started.md

CycloneDX.JSON has been marked as deprecated. Please provide an update for how to use the new structure. 

Thanks in advance.

**Comment by chaoscode** [comment]
I don't know why MS was listing it as deprecated but now it is not listed that way in nuget. Weird. Never mind.

**Comment by mtsfoni** [comment]
Are you confusing the namespace with the package name?

CycloneDX.Core is the correct library to use as laid down in getting-started.md
The CycloneDX.Json library is deprecated.
The C# `using CycloneDX.Json;` is used to access the Json-Namespace inside the CycloneDX.Core library.

**Comment by chaoscode** [comment]
No, it was just nuget being weird. I unloaded the solution and reloaded it and it stopped being reported as deprecated.

**Comment by chaoscode** [comment]
but thanks for this library. It is saving me a lot of time. <3
