### ISSUE TITLE
Workspace/AccessModeType has no null option

### ISSUE THREAD

**Issue by mtsfoni** [CycloneDX/cyclonedx-dotnet-library#357]
It's xsd definition allows it not to be set:
`<xs:element name="accessMode" type="bom:accessModeEnum" minOccurs="0" maxOccurs="1">`

But in the code we have neither a null enum option or a nullable option
```
        [ProtoContract]
        public enum AccessModeType
        {
            [XmlEnum(Name = "read-only")]
            Read_Only,
            [XmlEnum(Name = "read-write")]
            Read_Write,
            [XmlEnum(Name = "read-write-once")]
            Read_Write_Once,
            [XmlEnum(Name = "write-once")]
            Write_Once,
            [XmlEnum(Name = "write-only")]
            Write_Only,
        }
```

If it's not set, it will be set to `read-only` after deserialization and serialization.

**Comment by andreas-hilti** [comment]
I guess AccessMode should be changed to a nullable type.
